apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven
  labels:
    app: maven
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:         #NFS挂在选项
    - hard
    - nfsvers=4.1
  nfs:                  #NFS设置
    path: /home/nfs/data/maven
    server: 172.29.32.20
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: maven
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi     #存储空间大小
  selector:
    matchLabels:
      app: maven
